package com.gofirst.framework.bean;
// Generated 2017-7-18 8:53:23 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDict generated by hbm2java
 */
@Entity
@Table(name = "T_DICT")
public class TDict implements java.io.Serializable {

	private BigDecimal id;
	private String dictObject;
	private String dictName;
	private BigDecimal dictProperty;
	private String upObject;
	private String remark;
	private String delFlag;
	private String createUser;
	private Date createDate;
	private String updateUser;
	private Date updateDate;

	public TDict() {
	}

	public TDict(BigDecimal id) {
		this.id = id;
	}

	public TDict(BigDecimal id, String dictObject, String dictName, BigDecimal dictProperty, String upObject,
			String remark, String delFlag, String createUser, Date createDate, String updateUser, Date updateDate) {
		this.id = id;
		this.dictObject = dictObject;
		this.dictName = dictName;
		this.dictProperty = dictProperty;
		this.upObject = upObject;
		this.remark = remark;
		this.delFlag = delFlag;
		this.createUser = createUser;
		this.createDate = createDate;
		this.updateUser = updateUser;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "DICT_OBJECT", length = 20)
	public String getDictObject() {
		return this.dictObject;
	}

	public void setDictObject(String dictObject) {
		this.dictObject = dictObject;
	}

	@Column(name = "DICT_NAME", length = 200)
	public String getDictName() {
		return this.dictName;
	}

	public void setDictName(String dictName) {
		this.dictName = dictName;
	}

	@Column(name = "DICT_PROPERTY", precision = 15, scale = 4)
	public BigDecimal getDictProperty() {
		return this.dictProperty;
	}

	public void setDictProperty(BigDecimal dictProperty) {
		this.dictProperty = dictProperty;
	}

	@Column(name = "UP_OBJECT", length = 20)
	public String getUpObject() {
		return this.upObject;
	}

	public void setUpObject(String upObject) {
		this.upObject = upObject;
	}

	@Column(name = "REMARK", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "DEL_FLAG", length = 4)
	public String getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "CREATE_USER", length = 200)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_USER", length = 200)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
