package com.gofirst.framework.bean;
// Generated 2017-6-27 1:51:35 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TDict generated by hbm2java
 */
@Entity
@Table(name = "T_DICT", schema = "SHOP")
public class TDict implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String dictObject;
	private String dictName;
	private BigDecimal dictProperty;
	private String upObject;
	private String remark;
	private Character falg;

	public TDict() {
	}

	public TDict(String id) {
		this.id = id;
	}

	public TDict(String id, String dictObject, String dictName, BigDecimal dictProperty, String upObject, String remark,
			Character falg) {
		this.id = id;
		this.dictObject = dictObject;
		this.dictName = dictName;
		this.dictProperty = dictProperty;
		this.upObject = upObject;
		this.remark = remark;
		this.falg = falg;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "DICT_OBJECT", length = 20)
	public String getDictObject() {
		return this.dictObject;
	}

	public void setDictObject(String dictObject) {
		this.dictObject = dictObject;
	}

	@Column(name = "DICT_NAME", length = 200)
	public String getDictName() {
		return this.dictName;
	}

	public void setDictName(String dictName) {
		this.dictName = dictName;
	}

	@Column(name = "DICT_PROPERTY", precision = 15, scale = 4)
	public BigDecimal getDictProperty() {
		return this.dictProperty;
	}

	public void setDictProperty(BigDecimal dictProperty) {
		this.dictProperty = dictProperty;
	}

	@Column(name = "UP_OBJECT", length = 20)
	public String getUpObject() {
		return this.upObject;
	}

	public void setUpObject(String upObject) {
		this.upObject = upObject;
	}

	@Column(name = "REMARK", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "FALG", length = 1)
	public Character getFalg() {
		return this.falg;
	}

	public void setFalg(Character falg) {
		this.falg = falg;
	}

}
