package com.gofirst.framework.bean;
// Generated 2017-7-18 8:53:23 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * TOrder generated by hbm2java
 */
@Entity
@Table(name = "T_ORDER")
public class TOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	private BigDecimal id;
	@Column(name = "ORDER_NO", length = 100)
	private String orderNo;
	@Column(name = "ORDER_NAME", length = 200)
	private String orderName;
	@Column(name = "ORDER_OBJECT", length = 20)
	private String orderObject;
	@Column(name = "ORDER_STATUS", length = 1)
	private Character orderStatus;
	@Column(name = "ORDER_PRICE", precision = 15, scale = 4)
	private BigDecimal orderPrice;
	@Column(name = "ORDER_NUM", precision = 22, scale = 0)
	private BigDecimal orderNum;
	@Column(name = "ORDER_AMOUNT", precision = 20, scale = 4)
	private BigDecimal orderAmount;
	@Column(name = "FREE_NUM", precision = 22, scale = 0)
	private BigDecimal freeNum;
	@Column(name = "EXPRESS_NO", length = 100)
	private String expressNo;
	@Column(name = "EXPRESS_FEE", precision = 20, scale = 4)
	private BigDecimal expressFee;
	
	@JSONField(format="yyyy/MM/dd")
  	@Temporal(TemporalType.DATE)
	@Column(name = "BUY_DATE", length = 7)
	
	private Date buyDate;
	private String buyAddress;
	@Column(name = "REMARK", length = 2000)
	private String remark;
	@Column(name = "DEL_FLAG", length = 4)
	private String delFlag;
	@Column(name = "CREATE_USER", length = 200)
	private String createUser;
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	private Date createDate;
	@Column(name = "UPDATE_USER", length = 200)
	private String updateUser;
	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", length = 7)
	private Date updateDate;

	public TOrder() {
	}

	public TOrder(BigDecimal id) {
		this.id = id;
	}

	public TOrder(BigDecimal id, String orderNo, String orderName, String orderObject, Character orderStatus,
			BigDecimal orderPrice, BigDecimal orderNum, BigDecimal orderAmount, BigDecimal freeNum, String expressNo,
			BigDecimal expressFee, Date buyDate, String buyAddress, String remark, String delFlag, String createUser,
			Date createDate, String updateUser, Date updateDate) {
		this.id = id;
		this.orderNo = orderNo;
		this.orderName = orderName;
		this.orderObject = orderObject;
		this.orderStatus = orderStatus;
		this.orderPrice = orderPrice;
		this.orderNum = orderNum;
		this.orderAmount = orderAmount;
		this.freeNum = freeNum;
		this.expressNo = expressNo;
		this.expressFee = expressFee;
		this.buyDate = buyDate;
		this.buyAddress = buyAddress;
		this.remark = remark;
		this.delFlag = delFlag;
		this.createUser = createUser;
		this.createDate = createDate;
		this.updateUser = updateUser;
		this.updateDate = updateDate;
	}

	
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}


	public String getOrderName() {
		return this.orderName;
	}

	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

	
	public String getOrderObject() {
		return this.orderObject;
	}

	public void setOrderObject(String orderObject) {
		this.orderObject = orderObject;
	}

	
	public Character getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Character orderStatus) {
		this.orderStatus = orderStatus;
	}

	
	public BigDecimal getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

	
	public BigDecimal getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(BigDecimal orderNum) {
		this.orderNum = orderNum;
	}


	public BigDecimal getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	
	public BigDecimal getFreeNum() {
		return this.freeNum;
	}

	public void setFreeNum(BigDecimal freeNum) {
		this.freeNum = freeNum;
	}

	
	public String getExpressNo() {
		return this.expressNo;
	}

	public void setExpressNo(String expressNo) {
		this.expressNo = expressNo;
	}


	public BigDecimal getExpressFee() {
		return this.expressFee;
	}

	public void setExpressFee(BigDecimal expressFee) {
		this.expressFee = expressFee;
	}

	
	public Date getBuyDate() {
		return this.buyDate;
	}

	public void setBuyDate(Date buyDate) {
		this.buyDate = buyDate;
	}

	
	public String getBuyAddress() {
		return this.buyAddress;
	}

	public void setBuyAddress(String buyAddress) {
		this.buyAddress = buyAddress;
	}

	
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}


	public String getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "CREATE_USER", length = 200)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}


	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}


	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
