package com.gofirst.framework.bean;
// Generated 2017-6-27 1:51:35 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TOrder generated by hbm2java
 */
@Entity
@Table(name = "T_ORDER", schema = "SHOP")
public class TOrder implements java.io.Serializable {

	private String id;
	private String orderNo;
	private String orderName;
	private String orderObject;
	private Character orderStatus;
	private BigDecimal orderPrice;
	private BigDecimal orderNum;
	private BigDecimal orderAmount;
	private BigDecimal freeNum;
	private String expressNo;
	private BigDecimal expressFee;
	private String buyDate;
	private String buyAddress;
	private String remark;
	private Character flag;

	public TOrder() {
	}

	public TOrder(String id) {
		this.id = id;
	}

	public TOrder(String id, String orderNo, String orderName, String orderObject, Character orderStatus,
			BigDecimal orderPrice, BigDecimal orderNum, BigDecimal orderAmount, BigDecimal freeNum, String expressNo,
			BigDecimal expressFee, String buyDate, String buyAddress, String remark, Character flag) {
		this.id = id;
		this.orderNo = orderNo;
		this.orderName = orderName;
		this.orderObject = orderObject;
		this.orderStatus = orderStatus;
		this.orderPrice = orderPrice;
		this.orderNum = orderNum;
		this.orderAmount = orderAmount;
		this.freeNum = freeNum;
		this.expressNo = expressNo;
		this.expressFee = expressFee;
		this.buyDate = buyDate;
		this.buyAddress = buyAddress;
		this.remark = remark;
		this.flag = flag;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ORDER_NO", length = 100)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "ORDER_NAME", length = 200)
	public String getOrderName() {
		return this.orderName;
	}

	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

	@Column(name = "ORDER_OBJECT", length = 20)
	public String getOrderObject() {
		return this.orderObject;
	}

	public void setOrderObject(String orderObject) {
		this.orderObject = orderObject;
	}

	@Column(name = "ORDER_STATUS", length = 1)
	public Character getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Character orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "ORDER_PRICE", precision = 15, scale = 4)
	public BigDecimal getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

	@Column(name = "ORDER_NUM", precision = 22, scale = 0)
	public BigDecimal getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(BigDecimal orderNum) {
		this.orderNum = orderNum;
	}

	@Column(name = "ORDER_AMOUNT", precision = 20, scale = 4)
	public BigDecimal getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	@Column(name = "FREE_NUM", precision = 22, scale = 0)
	public BigDecimal getFreeNum() {
		return this.freeNum;
	}

	public void setFreeNum(BigDecimal freeNum) {
		this.freeNum = freeNum;
	}

	@Column(name = "EXPRESS_NO", length = 100)
	public String getExpressNo() {
		return this.expressNo;
	}

	public void setExpressNo(String expressNo) {
		this.expressNo = expressNo;
	}

	@Column(name = "EXPRESS_FEE", precision = 20, scale = 4)
	public BigDecimal getExpressFee() {
		return this.expressFee;
	}

	public void setExpressFee(BigDecimal expressFee) {
		this.expressFee = expressFee;
	}

	@Column(name = "BUY_DATE", length = 16)
	public String getBuyDate() {
		return this.buyDate;
	}

	public void setBuyDate(String buyDate) {
		this.buyDate = buyDate;
	}

	@Column(name = "BUY_ADDRESS", length = 2000)
	public String getBuyAddress() {
		return this.buyAddress;
	}

	public void setBuyAddress(String buyAddress) {
		this.buyAddress = buyAddress;
	}

	@Column(name = "REMARK", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "FLAG", length = 1)
	public Character getFlag() {
		return this.flag;
	}

	public void setFlag(Character flag) {
		this.flag = flag;
	}

}
