package com.gofirst.framework.bean;
// Generated 2017-7-18 8:53:23 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * TSettle generated by hbm2java
 */
@Entity
@Table(name = "T_SETTLE")
public class TSettle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private String settleNo;
	private String settleName;
	private Character settleStatus;
	private BigDecimal primePrice;
	private BigDecimal primeNum;
	private BigDecimal primeAmount;
	private BigDecimal expressFee;
	private BigDecimal ortherFee;
	private String ortherFeeReason;
	private BigDecimal orderAmount;
	private BigDecimal margin;
	private String remark;
	private String delFlag;
	private String createUser;
	private Date createDate;
	private String updateUser;
	private Date updateDate;

	public TSettle() {
	}

	public TSettle(BigDecimal id) {
		this.id = id;
	}

	public TSettle(BigDecimal id, String settleNo, String settleName, Character settleStatus, BigDecimal primePrice,
			BigDecimal primeNum, BigDecimal primeAmount, BigDecimal expressFee, BigDecimal ortherFee,
			String ortherFeeReason, BigDecimal orderAmount, BigDecimal margin, String remark, String delFlag,
			String createUser, Date createDate, String updateUser, Date updateDate) {
		this.id = id;
		this.settleNo = settleNo;
		this.settleName = settleName;
		this.settleStatus = settleStatus;
		this.primePrice = primePrice;
		this.primeNum = primeNum;
		this.primeAmount = primeAmount;
		this.expressFee = expressFee;
		this.ortherFee = ortherFee;
		this.ortherFeeReason = ortherFeeReason;
		this.orderAmount = orderAmount;
		this.margin = margin;
		this.remark = remark;
		this.delFlag = delFlag;
		this.createUser = createUser;
		this.createDate = createDate;
		this.updateUser = updateUser;
		this.updateDate = updateDate;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "SETTLE_NO", length = 100)
	public String getSettleNo() {
		return this.settleNo;
	}

	public void setSettleNo(String settleNo) {
		this.settleNo = settleNo;
	}

	@Column(name = "SETTLE_NAME", length = 200)
	public String getSettleName() {
		return this.settleName;
	}

	public void setSettleName(String settleName) {
		this.settleName = settleName;
	}

	@Column(name = "SETTLE_STATUS", length = 1)
	public Character getSettleStatus() {
		return this.settleStatus;
	}

	public void setSettleStatus(Character settleStatus) {
		this.settleStatus = settleStatus;
	}

	@Column(name = "PRIME_PRICE", precision = 15, scale = 4)
	public BigDecimal getPrimePrice() {
		return this.primePrice;
	}

	public void setPrimePrice(BigDecimal primePrice) {
		this.primePrice = primePrice;
	}

	@Column(name = "PRIME_NUM", precision = 22, scale = 0)
	public BigDecimal getPrimeNum() {
		return this.primeNum;
	}

	public void setPrimeNum(BigDecimal primeNum) {
		this.primeNum = primeNum;
	}

	@Column(name = "PRIME_AMOUNT", precision = 20, scale = 4)
	public BigDecimal getPrimeAmount() {
		return this.primeAmount;
	}

	public void setPrimeAmount(BigDecimal primeAmount) {
		this.primeAmount = primeAmount;
	}

	@Column(name = "EXPRESS_FEE", precision = 20, scale = 4)
	public BigDecimal getExpressFee() {
		return this.expressFee;
	}

	public void setExpressFee(BigDecimal expressFee) {
		this.expressFee = expressFee;
	}

	@Column(name = "ORTHER_FEE", precision = 15, scale = 4)
	public BigDecimal getOrtherFee() {
		return this.ortherFee;
	}

	public void setOrtherFee(BigDecimal ortherFee) {
		this.ortherFee = ortherFee;
	}

	@Column(name = "ORTHER_FEE_REASON", length = 200)
	public String getOrtherFeeReason() {
		return this.ortherFeeReason;
	}

	public void setOrtherFeeReason(String ortherFeeReason) {
		this.ortherFeeReason = ortherFeeReason;
	}

	@Column(name = "ORDER_AMOUNT", precision = 20, scale = 4)
	public BigDecimal getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	@Column(name = "MARGIN", precision = 20, scale = 4)
	public BigDecimal getMargin() {
		return this.margin;
	}

	public void setMargin(BigDecimal margin) {
		this.margin = margin;
	}

	@Column(name = "REMARK", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "DEL_FLAG", length = 4)
	public String getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "CREATE_USER", length = 200)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}
	@JSONField(format="yyyy/MM/dd")
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_USER", length = 200)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
	@JSONField(format="yyyy/MM/dd")
	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
