package com.gofirst.framework.bean;
// Generated 2017-6-27 1:51:35 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TSettle generated by hbm2java
 */
@Entity
@Table(name = "T_SETTLE", schema = "SHOP")
public class TSettle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String settleNo;
	private String settleName;
	private Character settleStatus;
	private BigDecimal primePrice;
	private BigDecimal primeNum;
	private BigDecimal primeAmount;
	private BigDecimal expressFee;
	private BigDecimal orderAmount;
	private BigDecimal margin;
	private String remark;
	private Character flag;

	public TSettle() {
	}

	public TSettle(String id) {
		this.id = id;
	}

	public TSettle(String id, String settleNo, String settleName, Character settleStatus, BigDecimal primePrice,
			BigDecimal primeNum, BigDecimal primeAmount, BigDecimal expressFee, BigDecimal orderAmount,
			BigDecimal margin, String remark, Character flag) {
		this.id = id;
		this.settleNo = settleNo;
		this.settleName = settleName;
		this.settleStatus = settleStatus;
		this.primePrice = primePrice;
		this.primeNum = primeNum;
		this.primeAmount = primeAmount;
		this.expressFee = expressFee;
		this.orderAmount = orderAmount;
		this.margin = margin;
		this.remark = remark;
		this.flag = flag;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "SETTLE_NO", length = 100)
	public String getSettleNo() {
		return this.settleNo;
	}

	public void setSettleNo(String settleNo) {
		this.settleNo = settleNo;
	}

	@Column(name = "SETTLE_NAME", length = 200)
	public String getSettleName() {
		return this.settleName;
	}

	public void setSettleName(String settleName) {
		this.settleName = settleName;
	}

	@Column(name = "SETTLE_STATUS", length = 1)
	public Character getSettleStatus() {
		return this.settleStatus;
	}

	public void setSettleStatus(Character settleStatus) {
		this.settleStatus = settleStatus;
	}

	@Column(name = "PRIME_PRICE", precision = 15, scale = 4)
	public BigDecimal getPrimePrice() {
		return this.primePrice;
	}

	public void setPrimePrice(BigDecimal primePrice) {
		this.primePrice = primePrice;
	}

	@Column(name = "PRIME_NUM", precision = 22, scale = 0)
	public BigDecimal getPrimeNum() {
		return this.primeNum;
	}

	public void setPrimeNum(BigDecimal primeNum) {
		this.primeNum = primeNum;
	}

	@Column(name = "PRIME_AMOUNT", precision = 20, scale = 4)
	public BigDecimal getPrimeAmount() {
		return this.primeAmount;
	}

	public void setPrimeAmount(BigDecimal primeAmount) {
		this.primeAmount = primeAmount;
	}

	@Column(name = "EXPRESS_FEE", precision = 20, scale = 4)
	public BigDecimal getExpressFee() {
		return this.expressFee;
	}

	public void setExpressFee(BigDecimal expressFee) {
		this.expressFee = expressFee;
	}

	@Column(name = "ORDER_AMOUNT", precision = 20, scale = 4)
	public BigDecimal getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	@Column(name = "MARGIN", precision = 20, scale = 4)
	public BigDecimal getMargin() {
		return this.margin;
	}

	public void setMargin(BigDecimal margin) {
		this.margin = margin;
	}

	@Column(name = "REMARK", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "FLAG", length = 1)
	public Character getFlag() {
		return this.flag;
	}

	public void setFlag(Character flag) {
		this.flag = flag;
	}

}
