package com.gofirst.framework.bean;
// Generated 2017-6-22 23:29:00 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name = "T_USER", schema = "SHOP")
public class TUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String userNo;
	private String userName;
	private String password;
	private String remark;
	private Character flag;

	public TUser() {
	}

	public TUser(String id) {
		this.id = id;
	}

	public TUser(String id, String userNo, String userName, String password, String remark, Character flag) {
		this.id = id;
		this.userNo = userNo;
		this.userName = userName;
		this.password = password;
		this.remark = remark;
		this.flag = flag;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "USER_NO", length = 100)
	public String getUserNo() {
		return this.userNo;
	}

	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	@Column(name = "USER_NAME", length = 200)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "REMARK", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "FLAG", length = 1)
	public Character getFlag() {
		return this.flag;
	}

	public void setFlag(Character flag) {
		this.flag = flag;
	}

}
